name: rio
version: 0.1.10.0
synopsis: A standard library for Haskell
description: See README and Haddocks at <https://www.stackage.org/package/rio>
license: MIT
author: Michael Snoyman
maintainer: michael@snoyman.com
github: commercialhaskell/rio
category: Control
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.10 && < 10
- bytestring
- containers
- deepseq
- directory
- exceptions
- filepath
- hashable
- microlens
- mtl
- primitive
- text
- time
- typed-process >= 0.2.2.0
- unliftio >= 0.2.8.0
- unliftio-core
- unordered-containers
- vector

# Just for preprocessor directives
- process

library:
  source-dirs: src/
  exposed-modules:
    - RIO
    - RIO.ByteString
    - RIO.ByteString.Lazy
    - RIO.ByteString.Lazy.Partial
    - RIO.ByteString.Partial
    - RIO.Char
    - RIO.Char.Partial
    - RIO.Deque
    - RIO.Directory
    - RIO.File
    - RIO.FilePath
    - RIO.HashMap
    - RIO.HashMap.Partial
    - RIO.HashSet
    - RIO.List
    - RIO.List.Partial
    - RIO.Map
    - RIO.Map.Partial
    - RIO.Map.Unchecked
    - RIO.Partial
    - RIO.Prelude
    - RIO.Prelude.Simple
    - RIO.Prelude.Types
    - RIO.Process
    - RIO.Seq
    - RIO.Set
    - RIO.Set.Partial
    - RIO.Set.Unchecked
    - RIO.State
    - RIO.Text
    - RIO.Text.Lazy
    - RIO.Text.Lazy.Partial
    - RIO.Text.Partial
    - RIO.Time
    - RIO.Vector
    - RIO.Vector.Boxed
    - RIO.Vector.Boxed.Partial
    - RIO.Vector.Boxed.Unsafe
    - RIO.Vector.Partial
    - RIO.Vector.Storable
    - RIO.Vector.Storable.Partial
    - RIO.Vector.Storable.Unsafe
    - RIO.Vector.Unboxed
    - RIO.Vector.Unboxed.Partial
    - RIO.Vector.Unboxed.Unsafe
    - RIO.Vector.Unsafe
    - RIO.Writer

  other-modules:
    - RIO.Prelude.Display
    - RIO.Prelude.Exit
    - RIO.Prelude.Extra
    - RIO.Prelude.IO
    - RIO.Prelude.Lens
    - RIO.Prelude.Logger
    - RIO.Prelude.Reexports
    - RIO.Prelude.Renames
    - RIO.Prelude.RIO
    - RIO.Prelude.Text
    - RIO.Prelude.Trace
    - RIO.Prelude.URef

  when:
  - condition: os(windows)
    then:
      cpp-options: -DWINDOWS
      dependencies:
      - Win32
    else:
      dependencies:
      - unix
      c-sources: cbits/rio.c
      cc-options: -Wall -O2

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - rio
    - hspec
    - QuickCheck
